highlighter: pygments
permalink: none
sass:
    style: :compressed
sections:
- about
- how-to-get-there
collections:
- sections
- participants
- participants_2015
- kiilopaa
- faq
defaults:
    -
        scope:
            path: "_participants"
        values:
            layout: "sub-page"
    -
        scope:
            path: "_participants-2015"
        values:
            layout: "sub-page"
