highlighter: pygments
permalink: none
sass:
    style: :compressed
sections:
- about
- how-to-get-there
collections:
- sections
- participants
- kiilopaa_sections
defaults:
 - 
   scope: 
     path: "_participants"
   values:
     layout: "sub-page"
